init rails app - first commit
wolox-training/jf-rails pull request #1
Opened 2018-05-30 21:08 UTC by floresv

### Summary

* Init rails app with version 5.1.6
* Add test folder to .gitignore file
* Setup connection, configuration and creation of postgres database

### Trello Card

https://trello.com/c/MSPI1oDq/16-crear-aplicaci%C3%B3n-rails-wbooksapi

2018-05-30 21:18 UTC, floresv commented
Disculpa el segundo commit, se me paso el gitignore

2018-05-31 18:18 UTC, leamotta requested changes
Just that tiny thing

2018-05-31 18:18 UTC, leamotta commented on config/application.rb
> +module JfRails
here you should have `WBooks` which is the name of the app. You need to explicitly specify the `WBooks` name or else it will use the folder name as the default

2018-05-31 19:02 UTC, floresv commented on config/application.rb
> +module JfRails
That's Right. I will do it.

2018-05-31 19:14 UTC, leamotta approved these changes

2018-05-31 19:16 UTC, merged