Feature index create rents
wolox-training/jf-rails pull request #13
Opened 2018-06-07 14:36 UTC by floresv

### Summary
Add testing and enpoints to index and create of Rents (by user or book)

### Trello Card
https://trello.com/c/lS9DcllY/32-crear-endpoint-de-creacion-de-rent-e-index

2018-06-07 19:17 UTC, leamotta requested changes

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        render_paginated(filtrate(rents), each_serializer: UserRentSerializer)
what if the params are not being sent correctly? `rents` would not exist 🤔

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        render_paginated(filtrate(rents), each_serializer: UserRentSerializer)
Also, you could extract some of the params logic in a private method.
Something like `rents = Rent.where(search_param)` where `search_param` is a function that handles the param dichotomy would avoid some of the code repetition for the rents

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        to = Date.parse(params['to'])
I don't think you need to `Date.parse` this params 🤔 , I could be wrong though

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        params.require(%i[book_id from to])
You don't need to change this, but as a rule with frontend, we always receive the entity that we're creating as an object, with its' params inside.
Something like `params.require(:rent).permit(:from, :to, :book_id)` is what we usually do

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        params.require(%i[book_id from to])
Also, the name of the function could be just `creation_params`

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        raise(ActionController::ParameterMissing.new(params), 'from > to') if from > to
You shouldn't need to raise this exception manually. The idea is that the model has this logic so you can avoid repeating it in the controller

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +                           to: params['to'])
A few things:
- It is generally better to build (not create) the Rent and then saving it, instead of just directly creating it. That way you can handle errors more easily. Here for example you could build it one line via the current_user `current_user.rents.build(creation_params)` with creation params obtaining and returning the parameters as it should be. 

- There is no need to do a find for the Book here, you should be able to use the id, and if it fails, let it fail and handle the error correctly.

- After you built the Rent, you can try saving it to the DB and then handle the success or the failure of that.
Something like `if rent.save` `a good response` (created status) else `a bad response` (422 status)

2018-06-07 19:17 UTC, leamotta commented on app/controllers/api_controller.rb
> +    render json: { error: 'Invalid params' }, status: :bad_request
Nice implementation!

2018-06-07 19:17 UTC, leamotta commented on app/serializers/user_rent_serializer.rb
> +class UserRentSerializer < ActiveModel::Serializer
This could be a Rent serializer, no need to associate it with the user

2018-06-07 19:17 UTC, leamotta commented on app/serializers/user_rent_serializer.rb
> +    UserSerializer.new(object.user).as_json
you can use `belongs_to :user` and `belongs_to :book` here, active model serializer understands that and should render the object with its serializer

2018-06-07 19:17 UTC, leamotta commented on spec/controllers/api/v1/rents_controller_spec.rb
> +      let!(:rents) { create_list(:rent, 3, user: user) }
what if there are more rents from another user? You should test that you only return the ones belonging to this user

2018-06-07 19:17 UTC, leamotta commented on spec/controllers/api/v1/rents_controller_spec.rb
> +    context 'When create a rent without a to date' do
copy paste here? :D

2018-06-07 19:17 UTC, leamotta commented on spec/controllers/api/v1/rents_controller_spec.rb
> +      end
It is also nice to test that you actually created it in the DB. Something like
`expect { Rent.count }.to change by(1)` (I'm not sure if that's 100% percent the correct syntax but you get the idea

2018-06-07 19:17 UTC, leamotta commented on spec/controllers/api/v1/rents_controller_spec.rb
> +      end
As with what I said in the other test, here you should test that you did not save anything to the database.

2018-06-07 19:17 UTC, leamotta commented on spec/controllers/api/v1/rents_controller_spec.rb
> +      end
Great selection of test cases!

2018-06-07 19:31 UTC, floresv commented on app/controllers/api/v1/rents_controller.rb
> +        render_paginated(filtrate(rents), each_serializer: UserRentSerializer)
If params don't have user_id or book_id, then is not match any route. In case that rents doesn't exists, It will respond with empty array.

2018-06-07 19:32 UTC, floresv commented on app/controllers/api/v1/rents_controller.rb
> +        to = Date.parse(params['to'])
Yes, because the comparison is with dates. If I don't parse it, is compared like strings.

2018-06-07 19:34 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        to = Date.parse(params['to'])
That is correct if you are validating that here, see my comment about the `raise` exception

2018-06-08 14:19 UTC, leamotta approved these changes
👍

2018-06-08 14:19 UTC, leamotta commented on app/controllers/api/v1/rents_controller.rb
> +        render(json: rent, serializer: RentSerializer)
remember to return the `:created` status on a create

2018-06-08 14:45 UTC, merged